[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
on_if = 'has("nvim")'
hook_source = 'source $XDG_VIM_HOME/plugins/deoplete.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1
on_if = '!has("nvim")'
hook_source = 'source $XDG_VIM_HOME/plugins/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
hook_source = 'source $XDG_VIM_HOME/plugins/neosnippet.vim'

[[plugins]]
repo = 'greyblake/vim-preview'
on_i = 1
